package io.tornnote;
import java.nio.charset.StandardCharsets;import java.security.*;import java.security.spec.ECGenParameterSpec;import java.util.*;
public final class TornNote{private TornNote(){}static final byte[]L="TORN-NOTE/leaf/v1".getBytes(StandardCharsets.UTF_8),T="TORN-NOTE/tx/v1".getBytes(StandardCharsets.UTF_8);public record Keys(KeyPair pair,String algorithm){}public record Note(byte[]id,Keys a,Keys b){}public record SignatureSet(byte[]master,byte[]a,byte[]b){}
public static Keys keys(String c)throws GeneralSecurityException{KeyPairGenerator g;if(c.equals("ed25519"))g=KeyPairGenerator.getInstance("Ed25519");else if(c.equals("p256")){g=KeyPairGenerator.getInstance("EC");g.initialize(new ECGenParameterSpec("secp256r1"));}else throw new IllegalArgumentException();return new Keys(g.generateKeyPair(),c);}
static byte[]h(byte[]...x)throws GeneralSecurityException{MessageDigest d=MessageDigest.getInstance("SHA-256");for(byte[]v:x)d.update(v);return d.digest();}public static byte[]pub(KeyPair k){return k.getPublic().getEncoded();}public static byte[]leaf(byte[]id,byte[]a,byte[]b)throws GeneralSecurityException{return h(L,id,a,b);}
public static byte[]root(List<byte[]>ls)throws GeneralSecurityException{if(ls.isEmpty())throw new IllegalArgumentException();List<byte[]>l=new ArrayList<>(ls);while(l.size()>1){List<byte[]>n=new ArrayList<>();for(int i=0;i<l.size();i+=2)n.add(h(l.get(i),i+1<l.size()?l.get(i+1):l.get(i)));l=n;}return l.get(0);}
public static List<byte[]>proof(List<byte[]>ls,int idx)throws GeneralSecurityException{List<byte[]>o=new ArrayList<>(),l=new ArrayList<>(ls);while(l.size()>1){int p=idx^1;o.add(p<l.size()?l.get(p):l.get(idx));List<byte[]>n=new ArrayList<>();for(int i=0;i<l.size();i+=2)n.add(h(l.get(i),i+1<l.size()?l.get(i+1):l.get(i)));idx/=2;l=n;}return o;}
public static boolean verifyMerkle(byte[]x,List<byte[]>p,byte[]r,int idx)throws GeneralSecurityException{for(byte[]v:p){x=(idx&1)==0?h(x,v):h(v,x);idx>>=1;}return MessageDigest.isEqual(x,r);}
public static byte[]digest(byte[]r,byte[]id,byte[]a,byte[]b,String p)throws GeneralSecurityException{return h(T,r,id,a,b,p.getBytes(StandardCharsets.UTF_8));}
static byte[]sign(PrivateKey k,byte[]d)throws GeneralSecurityException{Signature s=k.getAlgorithm().equalsIgnoreCase("EdDSA")||k.getAlgorithm().equalsIgnoreCase("Ed25519")?Signature.getInstance("Ed25519"):Signature.getInstance("SHA256withECDSA");s.initSign(k);s.update(d);return s.sign();}
static boolean verify(PublicKey k,byte[]d,byte[]z)throws GeneralSecurityException{Signature s=k.getAlgorithm().equalsIgnoreCase("EdDSA")||k.getAlgorithm().equalsIgnoreCase("Ed25519")?Signature.getInstance("Ed25519"):Signature.getInstance("SHA256withECDSA");s.initVerify(k);s.update(d);return s.verify(z);}
public static SignatureSet authorize(Keys m,Keys a,Keys b,byte[]r,byte[]id,byte[]pa,byte[]pb,String p,List<byte[]>pr,int i)throws GeneralSecurityException{if(!verifyMerkle(leaf(id,pa,pb),pr,r,i))throw new SecurityException();byte[]d=digest(r,id,pa,pb,p);return new SignatureSet(sign(m.pair().getPrivate(),d),sign(a.pair().getPrivate(),d),sign(b.pair().getPrivate(),d));}
public static boolean verifyAuthorization(PublicKey m,PublicKey a,PublicKey b,byte[]r,byte[]id,byte[]pa,byte[]pb,String p,List<byte[]>pr,int i,SignatureSet s,boolean spent)throws GeneralSecurityException{if(spent||!verifyMerkle(leaf(id,pa,pb),pr,r,i))return false;byte[]d=digest(r,id,pa,pb,p);return verify(m,d,s.master())&&verify(a,d,s.a())&&verify(b,d,s.b());}}